### ISSUE TITLE
Add "How it works" and "How to Sell Lif" buttons

### ISSUE THREAD

**Issue by AugustoL** [windingtree/mvm-stats#9]
Add a button that will redirect to the firsts question of the FAQ that will be:
"How it works"
"How to sell tokens back to the MVM"

This will be the main questions that the users will have.

@menschikov please review once we have them

**Comment by skkr** [comment]
@AugustoL since there are only two questions, I think it would be better (from a visual/functional design perspective) to keep only one button that link to the FAQ page. It also would be easier to handle if we need to add more questions later.

Please let me know if you think we can keep it this way or still want to have two buttons.
